version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: react-native-paper
    versions:
    - 4.7.1
    - 4.7.2
    - 4.8.0
  - dependency-name: expo-cli
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.6
    - 4.2.1
    - 4.3.0
    - 4.3.1
    - 4.3.2
    - 4.3.4
    - 4.3.5
    - 4.4.1
    - 4.4.3
  - dependency-name: expo
    versions:
    - 40.0.1
    - 41.0.0
  - dependency-name: react-redux
    versions:
    - 7.2.3
  - dependency-name: expo-web-browser
    versions:
    - 9.0.0
